### ISSUE TITLE
AnalyzeBehaviorspace interface is not showing up

### ISSUE THREAD

**Issue by Javiosorm** [jonathan-g/analyzeBehaviorspace#1]
Hi, I can install your `analyzeBehaviorspace` app without problem, but when I run the `launch_abs()` function, only "Launching analyzeBehaviorspace interface" is displayed in RStudio and nothing more happens (R version 4.1.0). What am I doing wrong? Thank you very much.

**Comment by j-magnolia** [comment]
I'm sorry that I didn't see this issue earlier. Can you run `sessionInfo()` from RStudio after you try and fail to run `launch_abs()` and paste the information into a comment here. I need to know what operating system and R configuration and what versions of the various packages you have.
